### ISSUE TITLE
Issues after 3.0.11 update

### ISSUE THREAD

**Issue by jdsirota** [crypto-browserify/pbkdf2#64]
I have the following section of code in my program, which was working before the update:

`var crypto = require('crypto')
/* istanbul ignore next */
if (crypto.pbkdf2Sync.toString().indexOf('keylen, digest') === -1) {
  throw new Error('Unsupported crypto version')
}`

After updating 3.0.11, pbkdf2Sync is undefined and so my code is failing. Any information on why this may be happening would be greatly appreciated.

**Comment by argshook** [comment]
hi, you can check #60

**Comment by Incanus3** [comment]
same issue, tried with 3.0.10 and that's broken as well.

**Comment by alirussell** [comment]
@Incanus3 i managed to get it working by forcing 3.0.9

**Comment by Incanus3** [comment]
So did I, after I finally found the source of the problem. At least this will force me to use yarn instead of npm. If I had yarn.lock, I could've found it much sooner.

**Comment by danbrianwhite** [comment]
The update to add this check completely breaks Webpack since it ultimately utilizes this package for crypto.

**Comment by calvinmetcalf** [comment]
shoulf be fixed

**Comment by danbrianwhite** [comment]
Not fixed. The problem is the core functionality in Webpack depends on this code not throwing an error. When the crypto.pbkdf2Sync value is undefined Webpack was OK with that especially if you did not really need to use the pbkdf2 method. When it throws an error, the code breaks running Webpack bundles.

**Comment by calvinmetcalf** [comment]
@danbrianwhite are you getting an error in version 3.0.12 and if so what is it?

**Comment by danbrianwhite** [comment]
@calvinmetcalf when crypto is required, it does not have the key pbkdf2Sync. This key is undefined which throws a JS error because the value is undefined. Even if that undefined value is checked for, it will still break Webpack because it expects not to be thrown and the code will now be thrown because of [this commit](https://github.com/crypto-browserify/pbkdf2/commit/5e63f63c149182f617b209d0419c408691b918d7#diff-168726dbe96b3ce427e7fedce31bb0bc)

**Comment by calvinmetcalf** [comment]
what exactly is your config,  that file shouldn't even be loaded in the first place because of the browser field in the package.json

**Comment by calvinmetcalf** [comment]
that's what #62 fixed

**Comment by danbrianwhite** [comment]
@calvinmetcalf Thank you for following up with me. The issue is indeed fixed now with v 3.0.12 - it looks like it took a little time to propagate through my cache. Thank you for fixing the issue.

**Comment by dcousens** [comment]
@calvinmetcalf seems like you had fun overnight.
Everything looks good now?

Anything published/unpublished?

**Comment by calvinmetcalf** [comment]
I believe it's all fine now

**Comment by calvinmetcalf** [comment]
basically I forgot to update browser object so it was pointing at the wrong file
